export enum ActionTypes {
  CLEAN_GAME = 'CLEAN_GAME',
  GET_WORD_OF_THE_DAY = 'GET_WORD_OF_THE_DAY',
  ON_WORD_OF_THE_DAY_SUCCESS = 'ON_WORD_OF_THE_DAY_SUCCESS',
  SET_KEYBOARD = 'SET_KEYBOARD',
  CHECK_WORD_REQUEST = 'CHECK_WORD_REQUEST',
  ON_CHECK_WORD_SUCCESS = 'ON_CHECK_WORD_SUCCESS',
  CHECK_WORD_ERROR = 'CHECK_WORD_ERROR',
  CLOSE_GAME = 'CLOSE_GAME',
  SETUP_GAME_CONFIG = 'SETUP_GAME_CONFIG',
  ENTER_WORD = 'ENTER_WORD',
  UPDATE_CURRENT_LINE = 'UPDATE_CURRENT_LINE',
  DELETE_WORD = 'DELETE_WORD',
}
