export enum ActionTypes {
  CLEAN_SETTING = 'CLEAN_SETTING',
  SET_SOUNDTRACK_STATUS = 'SET_SOUNDTRACK_STATUS',
  UPDATE_WORD_OF_DAY_LAST_TIME = 'UPDATE_WORD_OF_DAY_LAST_TIME',
  WRONG_WORD_REQUEST = 'WRONG_WORD_REQUEST',
  ON_WRONG_WORD_SUCCESS = 'ON_WRONG_WORD_SUCCESS',
}
