export enum ActionTypes {
  CLEAN_TOURNAMENT = 'CLEAN_TOURNAMENT',
  SET_TOURNAMENT_CONFIG = 'SET_TOURNAMENT_CONFIG',
  UPDATE_TOURNAMENT_CONFIG = 'UPDATE_TOURNAMENT_CONFIG',
  UPDATE_SCORE = 'UPDATE_SCORE',
}
