export enum ActionTypes {
  CLEAN_APP = 'CLEAN_APP',
  STARTUP = 'STARTUP',
  SERVER_IS_READY = 'SERVER_IS_READY',
  LOGIN_REQUEST = 'LOGIN_REQUEST',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_ERROR = 'LOGIN_ERROR',
  LOGOUT = 'LOGOUT',
  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
}
