export enum Colors {
  TRANSPARENT = 'transparent',
  SESAME_STREET_GREEN = '#00a870',
  ELECTION_NIGHT = '#120626',
  BLUEBONNET = '#1c1cf0',
  SUNSET_RIDERS = '#d70040',
  OCEAN_STORM = '#3d6a7f',
  CARROT_ORANGE = '#ed9121',
  TROLL_SLAYER_ORANGE = '#f5a34c',
  CATERPILLAR_GREEN = '#186d4a',
  SNOW_BALLET = '#def1e6',
  DEEP_FIR = '#163727',
  SPEARMINTS = '#bce3cd',
  ANGEL_HAIR_SILVER = '#d3d6da',
  VEGAS_GOLD = '#c9b458',
  TARNISHED_SILVER = '#787c7e',
  FERNTASTIC = '#6aaa64',
  WHITE = '#ffffff',
}

export enum LightColors {
  ACTIVITY_INDICATOR = Colors.ELECTION_NIGHT,
  BACKGROUND = Colors.SNOW_BALLET,
  // text
  MAIN_TEXT = Colors.DEEP_FIR,
  SECONDARY_TEXT = Colors.SNOW_BALLET,
  LINK_TEXT = Colors.BLUEBONNET,
  ERROR_TEXT = Colors.SUNSET_RIDERS,
  // buttons
  STATIC_BUTTONS = Colors.SESAME_STREET_GREEN,
  PRESSED_BUTTONS = Colors.CATERPILLAR_GREEN,
  STATIC_SECONDARY_BUTTONS = Colors.CARROT_ORANGE,
  PRESSED_SECONDARY_BUTTONS = Colors.TROLL_SLAYER_ORANGE,
  BUTTONS_LOADER = Colors.TRANSPARENT,
  TRANSPARENT_BUTTONS = Colors.TRANSPARENT,
  // inputs
  PLACEHOLDER_INPUT = Colors.OCEAN_STORM,
  DISABLE_INPUT = Colors.OCEAN_STORM,
  BACKGROUND_INPUT = Colors.SPEARMINTS,
  ERROR_INPUT = Colors.SUNSET_RIDERS,
  TRANSPARENT_INPUT = Colors.TRANSPARENT,
  BORDER_INPUT = Colors.CATERPILLAR_GREEN,
  // modals
  MODAL_BACKGROUND = Colors.OCEAN_STORM,
  MODAL_CONTAINER_BACKGROUND = Colors.SNOW_BALLET,
  // toasts
  SUCCESS_BACKGROUND_TOAST = Colors.CATERPILLAR_GREEN,
  ERROR_BACKGROUND_TOAST = Colors.SUNSET_RIDERS,
  // icons
  SECURE_EYE_PASS_ICON = Colors.DEEP_FIR,
  EXIT_ICON = Colors.CATERPILLAR_GREEN,
  WINNER_ICON = Colors.CATERPILLAR_GREEN,
  LOSER_ICON = Colors.CARROT_ORANGE,
  // items
  BACKGROUND_ITEMS = Colors.OCEAN_STORM,
  TITLE_ITEMS = Colors.TROLL_SLAYER_ORANGE,
  TABLE_ITEM_BACKGROUND = Colors.WHITE,
  // keyboard
  BACKGROUND_KEYBOARD = Colors.ANGEL_HAIR_SILVER,
  COINCIDENCE_BACKGROUND_KEYBOARD = Colors.VEGAS_GOLD,
  MISSING_BACKGROUND_KEYBOARD = Colors.TARNISHED_SILVER,
  RIGHT_TARGET_BACKGROUND_KEYBOARD = Colors.FERNTASTIC,
}
