name: build_artifacts_on_android

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - master


jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: Build release APK
        run: |
          cd android && ./gradlew clean && ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
